version: '3.8'

services:
  chat-app:
    image: chat-app:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5001:5001
    networks:
      - chat-app

networks:
  chat-app:
    driver: bridge

